<?php

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            0 => array('quantity' => '10', 'name' => 'BRAKE CABLE HONDA', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            1 => array('quantity' => '10', 'name' => 'BEARING 6004', 'buying_price' => '50', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            2 => array('quantity' => '10', 'name' => 'BEARING 6200', 'buying_price' => '40', 'selling_price' => '60', 'min' => '5', 'max' => '15'),
            3 => array('quantity' => '10', 'name' => 'BEARING 6202', 'buying_price' => '45', 'selling_price' => '70', 'min' => '5', 'max' => '15'),
            4 => array('quantity' => '10', 'name' => 'BEARING 6300', 'buying_price' => '45', 'selling_price' => '60', 'min' => '5', 'max' => '15'),
            5 => array('quantity' => '10', 'name' => 'BEARING 6301', 'buying_price' => '45', 'selling_price' => '70', 'min' => '5', 'max' => '15'),
            6 => array('quantity' => '10', 'name' => 'BEARING 6302', 'buying_price' => '50', 'selling_price' => '70', 'min' => '5', 'max' => '15'),
            7 => array('quantity' => '3', 'name' => 'BRAKE PEDAL BJJ', 'buying_price' => '170', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            8 => array('quantity' => '3', 'name' => 'BRAKE PEDAL BM', 'buying_price' => '170', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            9 => array('quantity' => '3', 'name' => 'BRAKE PEDAL TVS', 'buying_price' => '170', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            10 => array('quantity' => '5', 'name' => 'BRAKE ROD BJJ', 'buying_price' => '50', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            11 => array('quantity' => '5', 'name' => 'BRAKE ROD BM', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            12 => array('quantity' => '3', 'name' => 'BRAKE ROD HONDA', 'buying_price' => '100', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            13 => array('quantity' => '5', 'name' => 'BRAKE ROD TVS', 'buying_price' => '50', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            14 => array('quantity' => '30', 'name' => 'MOTORCYCLE BULB RED BOX', 'buying_price' => '22', 'selling_price' => '100', 'min' => '9', 'max' => '45'),
            15 => array('quantity' => '10', 'name' => 'BULB/LAMP HOLDER TVS', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            16 => array('quantity' => '5', 'name' => 'STEERING BUSH(BUSHES ZA KICHWA)', 'buying_price' => '15', 'selling_price' => '20', 'min' => '5', 'max' => '15'),
            17 => array('quantity' => '5', 'name' => 'BUSHES TVS', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            18 => array('quantity' => '60', 'name' => 'BUSHES TVS JUAKALI', 'buying_price' => '0', 'selling_price' => '150', 'min' => '18', 'max' => '90'),
            19 => array('quantity' => '10', 'name' => 'ACCELERATOR CABLE BJJ', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            20 => array('quantity' => '10', 'name' => 'ACCELERATOR CABLE BM', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            21 => array('quantity' => '10', 'name' => 'ACCELERATOR CABLE HONDA', 'buying_price' => '80', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            22 => array('quantity' => '10', 'name' => 'ACCELERATOR CABLE TVS', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            23 => array('quantity' => '10', 'name' => 'BRAKE CABLE BJJ', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            24 => array('quantity' => '10', 'name' => 'BRAKE CABLE BM', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            25 => array('quantity' => '10', 'name' => 'BRAKE CABLE TVS', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            26 => array('quantity' => '10', 'name' => 'CLUTCH CABLE BJJ', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            27 => array('quantity' => '10', 'name' => 'CLUTCH CABLE BM', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            28 => array('quantity' => '10', 'name' => 'CLUTCH CABLE HONDA', 'buying_price' => '80', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            29 => array('quantity' => '10', 'name' => 'CLUTCH CABLE  TVS', 'buying_price' => '70', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            30 => array('quantity' => '10', 'name' => 'CLUTCH GASKET TVS', 'buying_price' => '30', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            31 => array('quantity' => '2', 'name' => 'CLUTCH DISK/HOUSING BM', 'buying_price' => '350', 'selling_price' => '600', 'min' => '5', 'max' => '15'),
            32 => array('quantity' => '2', 'name' => 'CLUTCH DISK/HOUSING TVS', 'buying_price' => '350', 'selling_price' => '500', 'min' => '5', 'max' => '15'),
            33 => array('quantity' => '2', 'name' => 'CLUTCH DISK/HOUSING BJJ', 'buying_price' => '350', 'selling_price' => '600', 'min' => '5', 'max' => '15'),
            34 => array('quantity' => '9', 'name' => 'CLUTCH WIRE', 'buying_price' => '0', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            35 => array('quantity' => '10', 'name' => 'CYLINDER GASKET TVS', 'buying_price' => '30', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            36 => array('quantity' => '10', 'name' => 'CYLINDER GASKET BJJ', 'buying_price' => '30', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            37 => array('quantity' => '1', 'name' => 'DASHBOARD BJJ NEW', 'buying_price' => '650', 'selling_price' => '800', 'min' => '5', 'max' => '15'),
            38 => array('quantity' => '2', 'name' => 'DASHBOARD TVS', 'buying_price' => '440', 'selling_price' => '550', 'min' => '5', 'max' => '15'),
            39 => array('quantity' => '1', 'name' => 'DASHBOARD HONDA', 'buying_price' => '650', 'selling_price' => '800', 'min' => '5', 'max' => '15'),
            40 => array('quantity' => '1', 'name' => 'DIMMER SWITCH COMPLETE BJJ', 'buying_price' => '450', 'selling_price' => '600', 'min' => '5', 'max' => '15'),
            41 => array('quantity' => '2', 'name' => 'DIMMER SWITCH COMPLETE TVS', 'buying_price' => '500', 'selling_price' => '700', 'min' => '5', 'max' => '15'),
            42 => array('quantity' => '1', 'name' => 'FOOT REST COMPLETE TVS', 'buying_price' => '500', 'selling_price' => '700', 'min' => '5', 'max' => '15'),
            43 => array('quantity' => '5', 'name' => 'FOOTREST RUBBERS TVS', 'buying_price' => '60', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            44 => array('quantity' => '12', 'name' => 'FRONT SPROCKET STAR 125', 'buying_price' => '50', 'selling_price' => '100', 'min' => '5', 'max' => '18'),
            45 => array('quantity' => '8', 'name' => 'FRONT SPROCKET TVS(BLUE)', 'buying_price' => '50', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            46 => array('quantity' => '2', 'name' => 'GASKETS TVS', 'buying_price' => '100', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            47 => array('quantity' => '2', 'name' => 'GASKETS BJJ', 'buying_price' => '100', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            48 => array('quantity' => '2', 'name' => 'GASKETS BM', 'buying_price' => '100', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            49 => array('quantity' => '3', 'name' => 'GEAR LEVER HONDA', 'buying_price' => '150', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            50 => array('quantity' => '5', 'name' => 'GEAR LEVER TVS', 'buying_price' => '130', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            51 => array('quantity' => '3', 'name' => 'GEAR LEVER BJJ', 'buying_price' => '130', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            52 => array('quantity' => '5', 'name' => 'HEAD BULB BM H4', 'buying_price' => '45', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            53 => array('quantity' => '30', 'name' => 'HEAD BULB TVS', 'buying_price' => '0', 'selling_price' => '100', 'min' => '9', 'max' => '45'),
            54 => array('quantity' => '3', 'name' => 'HEAD LAMP COMPLETE TVS', 'buying_price' => '450', 'selling_price' => '550', 'min' => '5', 'max' => '15'),
            55 => array('quantity' => '10', 'name' => 'BULB HOLDERS', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            56 => array('quantity' => '3', 'name' => 'DOOMS/HOUSING BJJ', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            57 => array('quantity' => '5', 'name' => 'DOOMS/HOUSING BM', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            58 => array('quantity' => '5', 'name' => 'DOOMS/HOUSING HONDA', 'buying_price' => '100', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            59 => array('quantity' => '5', 'name' => 'DOOMS/HOUSING TVS', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            60 => array('quantity' => '3', 'name' => 'IGNITION KEY BJJ NEW', 'buying_price' => '300', 'selling_price' => '350', 'min' => '5', 'max' => '15'),
            61 => array('quantity' => '12', 'name' => 'INDICATOR BJJ               PC', 'buying_price' => '280', 'selling_price' => '100', 'min' => '5', 'max' => '18'),
            62 => array('quantity' => '20', 'name' => 'INDICATOR BULB           PC', 'buying_price' => '8', 'selling_price' => '20', 'min' => '6', 'max' => '30'),
            63 => array('quantity' => '12', 'name' => 'INDICATOR LX                PC', 'buying_price' => '280', 'selling_price' => '100', 'min' => '5', 'max' => '18'),
            64 => array('quantity' => '12', 'name' => 'INDICATOR TVS           PC', 'buying_price' => '280', 'selling_price' => '100', 'min' => '5', 'max' => '18'),
            65 => array('quantity' => '1', 'name' => 'LEAD WIRE 100M          1PC', 'buying_price' => '850', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            66 => array('quantity' => '10', 'name' => 'BRAKE SHOE/LININGS BM/HONDA YOG', 'buying_price' => '160', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            67 => array('quantity' => '10', 'name' => 'BRAKE SHOE/LINING TVS                  YOG', 'buying_price' => '120', 'selling_price' => '180', 'min' => '5', 'max' => '15'),
            68 => array('quantity' => '10', 'name' => 'OIL ADVANCE', 'buying_price' => '325', 'selling_price' => '350', 'min' => '5', 'max' => '15'),
            69 => array('quantity' => '9', 'name' => 'OIL CLASSIC', 'buying_price' => '273', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            70 => array('quantity' => '10', 'name' => 'OIL HONDA', 'buying_price' => '470', 'selling_price' => '500', 'min' => '5', 'max' => '15'),
            71 => array('quantity' => '10', 'name' => 'OIL FILTER', 'buying_price' => '55', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            72 => array('quantity' => '10', 'name' => 'PLUG CUPS', 'buying_price' => '40', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            73 => array('quantity' => '2', 'name' => 'PLUG HONDA', 'buying_price' => '0', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            74 => array('quantity' => '1', 'name' => 'PLUG TVS YOG', 'buying_price' => '0', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            75 => array('quantity' => '5', 'name' => 'REAR SPROCKET BM', 'buying_price' => '200', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            76 => array('quantity' => '5', 'name' => 'REAR SPROCKET TVS', 'buying_price' => '200', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            77 => array('quantity' => '10', 'name' => 'RINGS HONDA', 'buying_price' => '150', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            78 => array('quantity' => '10', 'name' => 'RINGS TVS', 'buying_price' => '140', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            79 => array('quantity' => '10', 'name' => 'RINGS BJJ', 'buying_price' => '140', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            80 => array('quantity' => '10', 'name' => 'RINGS BM', 'buying_price' => '150', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            81 => array('quantity' => '10', 'name' => 'SHOCK OIL', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            82 => array('quantity' => '10', 'name' => 'SHOCK SEALS BM', 'buying_price' => '80', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            83 => array('quantity' => '10', 'name' => 'SHOCK SEALS TVS', 'buying_price' => '60', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            84 => array('quantity' => '10', 'name' => 'SIDE MIRROR BJJ', 'buying_price' => '165', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            85 => array('quantity' => '10', 'name' => 'SIDE MIRROR TVS', 'buying_price' => '165', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            86 => array('quantity' => '10', 'name' => 'SILICON', 'buying_price' => '45', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            87 => array('quantity' => '3', 'name' => 'SITTING SPROCKET TVS', 'buying_price' => '330', 'selling_price' => '450', 'min' => '5', 'max' => '15'),
            88 => array('quantity' => '10', 'name' => 'SPRING MAIN STAND', 'buying_price' => '20', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            89 => array('quantity' => '10', 'name' => 'BRAKE SPRING', 'buying_price' => '20', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            90 => array('quantity' => '10', 'name' => 'SPRING SIDE STAND', 'buying_price' => '20', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            91 => array('quantity' => '4', 'name' => 'SPROCKET SET BJJ', 'buying_price' => '650', 'selling_price' => '750', 'min' => '5', 'max' => '15'),
            92 => array('quantity' => '4', 'name' => 'SPROCKET SET BM', 'buying_price' => '680', 'selling_price' => '800', 'min' => '5', 'max' => '15'),
            93 => array('quantity' => '4', 'name' => 'SPROCKET SET HONDA', 'buying_price' => '700', 'selling_price' => '800', 'min' => '5', 'max' => '15'),
            94 => array('quantity' => '4', 'name' => 'SPROCKET SET TVS', 'buying_price' => '640', 'selling_price' => '750', 'min' => '5', 'max' => '15'),
            95 => array('quantity' => '48', 'name' => 'SUPER GLUE', 'buying_price' => '21', 'selling_price' => '40', 'min' => '14', 'max' => '72'),
            96 => array('quantity' => '30', 'name' => 'TAIL BULB', 'buying_price' => '20', 'selling_price' => '100', 'min' => '9', 'max' => '45'),
            97 => array('quantity' => '40', 'name' => 'WASHER 8/10', 'buying_price' => '3', 'selling_price' => '10', 'min' => '12', 'max' => '60'),
            98 => array('quantity' => '40', 'name' => 'WASHER 13/14', 'buying_price' => '3', 'selling_price' => '20', 'min' => '12', 'max' => '60'),
            99 => array('quantity' => '3', 'name' => 'BRAKELIGHTS COMPLETE TVS', 'buying_price' => '250', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            100 => array('quantity' => '3', 'name' => 'TAIL LENCE TVS', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            101 => array('quantity' => '3', 'name' => 'TAIL LENCE BAJAJ', 'buying_price' => '100', 'selling_price' => '150', 'min' => '5', 'max' => '15'),
            102 => array('quantity' => '5', 'name' => 'TAPE', 'buying_price' => '150', 'selling_price' => '30', 'min' => '5', 'max' => '15'),
            103 => array('quantity' => '10', 'name' => 'TUBES 17', 'buying_price' => '160', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            104 => array('quantity' => '10', 'name' => 'TUBES 18', 'buying_price' => '160', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            105 => array('quantity' => '10', 'name' => 'VALVES HONDA', 'buying_price' => '180', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            106 => array('quantity' => '10', 'name' => 'VALVES TVS YOG', 'buying_price' => '140', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            107 => array('quantity' => '2', 'name' => 'PISTON KITS TVS', 'buying_price' => '400', 'selling_price' => '500', 'min' => '5', 'max' => '15'),
            108 => array('quantity' => '10', 'name' => 'BLOCK GASKET TVS', 'buying_price' => '25', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            109 => array('quantity' => '10', 'name' => 'BLOCK GASKET BAJAJ', 'buying_price' => '25', 'selling_price' => '50', 'min' => '5', 'max' => '15'),
            110 => array('quantity' => '5', 'name' => 'CLUTCH LEVER BM/HANDLES BM', 'buying_price' => '130', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            111 => array('quantity' => '8', 'name' => 'CLUTCH LEVER /HANDLE CABLE HONDA', 'buying_price' => '180', 'selling_price' => '300', 'min' => '5', 'max' => '15'),
            112 => array('quantity' => '1', 'name' => 'TYRE 18 CC 3.00', 'buying_price' => '1450', 'selling_price' => '1600', 'min' => '5', 'max' => '15'),
            113 => array('quantity' => '1', 'name' => 'TYRE 18CC 2.75', 'buying_price' => '950', 'selling_price' => '1200', 'min' => '5', 'max' => '15'),
            114 => array('quantity' => '2', 'name' => 'TYRE 17 CC 2.75', 'buying_price' => '950', 'selling_price' => '1200', 'min' => '5', 'max' => '15'),
            115 => array('quantity' => '2', 'name' => 'TYRE 17 CC 3.00', 'buying_price' => '1400', 'selling_price' => '1600', 'min' => '5', 'max' => '15'),
            116 => array('quantity' => '3', 'name' => 'SNAKE LIGHTS', 'buying_price' => '130', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            117 => array('quantity' => '10', 'name' => 'PATCH SIZE 48', 'buying_price' => '60', 'selling_price' => '80', 'min' => '5', 'max' => '15'),
            118 => array('quantity' => '10', 'name' => 'PATCH SIZE 24', 'buying_price' => '60', 'selling_price' => '80', 'min' => '5', 'max' => '15'),
            119 => array('quantity' => '30', 'name' => 'STRIPES', 'buying_price' => '5', 'selling_price' => '10', 'min' => '9', 'max' => '45'),
            120 => array('quantity' => '1', 'name' => 'BATTERY N2.5 TVS –SMALL BAJAJ', 'buying_price' => '600', 'selling_price' => '700', 'min' => '5', 'max' => '15'),
            121 => array('quantity' => '1', 'name' => 'BATTERY BIG  N6.5 -BM', 'buying_price' => '1000', 'selling_price' => '1200', 'min' => '5', 'max' => '15'),
            122 => array('quantity' => '10', 'name' => 'SHARP LIGHTS', 'buying_price' => '55', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            123 => array('quantity' => '8', 'name' => 'LED LIGHTS', 'buying_price' => '150', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            124 => array('quantity' => '5', 'name' => 'CLUTCH PLATE TVS', 'buying_price' => '140', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            125 => array('quantity' => '5', 'name' => 'CLUTCH PLATE BAJAJ', 'buying_price' => '140', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            126 => array('quantity' => '5', 'name' => 'CLUTCH PLATE BM', 'buying_price' => '160', 'selling_price' => '250', 'min' => '5', 'max' => '15'),
            127 => array('quantity' => '20', 'name' => 'BOLTS 10 ¼ INCH', 'buying_price' => '5', 'selling_price' => '10', 'min' => '6', 'max' => '30'),
            128 => array('quantity' => '20', 'name' => 'BOLTS 10 INCH', 'buying_price' => '5', 'selling_price' => '10', 'min' => '6', 'max' => '30'),
            129 => array('quantity' => '20', 'name' => 'BOLTS 13 INCH', 'buying_price' => '10', 'selling_price' => '20', 'min' => '6', 'max' => '30'),
            130 => array('quantity' => '20', 'name' => 'BOLTS 13 ½ INCH', 'buying_price' => '10', 'selling_price' => '20', 'min' => '6', 'max' => '30'),
            131 => array('quantity' => '10', 'name' => 'HANDLE GRIPS', 'buying_price' => '70', 'selling_price' => '100', 'min' => '5', 'max' => '15'),
            132 => array('quantity' => '10', 'name' => 'VALVES BJJ YOG', 'buying_price' => '150', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            133 => array('quantity' => '5', 'name' => 'VALVES BM 150 YOG', 'buying_price' => '150', 'selling_price' => '200', 'min' => '5', 'max' => '15'),
            134 => array('quantity' => '3', 'name' => 'TAIL LENS COMPLETE BJJ', 'buying_price' => '0', 'selling_price' => '0', 'min' => '5', 'max' => '15'),
            135 => array('quantity' => '3', 'name' => 'TAIL LENS COMPLETE TVS', 'buying_price' => '0', 'selling_price' => '0', 'min' => '5', 'max' => '15'),
        );

        if (Product::count() === 0) {
            foreach ($products as $product) {
                $created_product = Product::create([
                    'name' => $product['name'],
                    'buying_price' => $product['buying_price'],
                    'buying_price_currency' => 'KES',
                    'selling_price_currency' => 'KES',
                    'selling_price' => $product['selling_price'],
                    'min' => $product['min'],
                    'max' => $product['max']
                ]);
                $created_product->purchases()->create([
                    'quantity' => $product['quantity'],
                    'unit_price' => $product['buying_price'],
                    'currency' => 'KES',
                    'purchase_date' => '2020-02-13'
                ]);
            }
        }
    }
}
