<?php

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            0 => array('name' => 'accelerator cg cable', 'quantity' => '30', 'buying_price' => '70', 'selling_price' => '150', 'min' => '45', 'max' => '9'),
            1 => array('name' => 'aerial', 'quantity' => '4', 'buying_price' => '130', 'selling_price' => '200', 'min' => '8', 'max' => '3'),
            2 => array('name' => 'air cleaner sponge', 'quantity' => '1', 'buying_price' => '100', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            3 => array('name' => 'ball  race', 'quantity' => '7', 'buying_price' => '120', 'selling_price' => '300', 'min' => '11', 'max' => '3'),
            4 => array('name' => 'ball race bm150', 'quantity' => '10', 'buying_price' => '120', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            5 => array('name' => 'base gasket cg150', 'quantity' => '134', 'buying_price' => '25', 'selling_price' => '50', 'min' => '201', 'max' => '40'),
            6 => array('name' => 'batteries bajaj', 'quantity' => '3', 'buying_price' => '1000', 'selling_price' => '1400', 'min' => '8', 'max' => '3'),
            7 => array('name' => 'batteries cg 150', 'quantity' => '6', 'buying_price' => '1200', 'selling_price' => '1600', 'min' => '9', 'max' => '3'),
            8 => array('name' => 'bearing 6300', 'quantity' => '10', 'buying_price' => '50', 'selling_price' => '100', 'min' => '15', 'max' => '3'),
            9 => array('name' => 'bearings 6002', 'quantity' => '20', 'buying_price' => '35', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            10 => array('name' => 'bearings 6003', 'quantity' => '20', 'buying_price' => '40', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            11 => array('name' => 'bearings 6004', 'quantity' => '19', 'buying_price' => '50', 'selling_price' => '150', 'min' => '29', 'max' => '6'),
            12 => array('name' => 'bearings 6200', 'quantity' => '29', 'buying_price' => '50', 'selling_price' => '100', 'min' => '44', 'max' => '9'),
            13 => array('name' => 'bearings 6201', 'quantity' => '21', 'buying_price' => '35', 'selling_price' => '100', 'min' => '32', 'max' => '6'),
            14 => array('name' => 'bearings 6202', 'quantity' => '14', 'buying_price' => '50', 'selling_price' => '100', 'min' => '21', 'max' => '4'),
            15 => array('name' => 'bearings 6301', 'quantity' => '23', 'buying_price' => '50', 'selling_price' => '100', 'min' => '35', 'max' => '7'),
            16 => array('name' => 'bearings 6302', 'quantity' => '31', 'buying_price' => '50', 'selling_price' => '100', 'min' => '47', 'max' => '9'),
            17 => array('name' => 'block tensioner bm150', 'quantity' => '2', 'buying_price' => '250', 'selling_price' => '400', 'min' => '8', 'max' => '3'),
            18 => array('name' => 'bolt no 10', 'quantity' => '150', 'buying_price' => '5', 'selling_price' => '10', 'min' => '225', 'max' => '45'),
            19 => array('name' => 'bolt no 13', 'quantity' => '30', 'buying_price' => '10', 'selling_price' => '20', 'min' => '45', 'max' => '9'),
            20 => array('name' => 'bolt no 14', 'quantity' => '20', 'buying_price' => '20', 'selling_price' => '40', 'min' => '30', 'max' => '6'),
            21 => array('name' => 'bolt no 8', 'quantity' => '150', 'buying_price' => '5', 'selling_price' => '10', 'min' => '225', 'max' => '45'),
            22 => array('name' => 'brake pedal bm150', 'quantity' => '7', 'buying_price' => '220', 'selling_price' => '400', 'min' => '11', 'max' => '3'),
            23 => array('name' => 'brake switch spring', 'quantity' => '26', 'buying_price' => '12', 'selling_price' => '30', 'min' => '39', 'max' => '8'),
            24 => array('name' => 'break cable bm150', 'quantity' => '5', 'buying_price' => '80', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            25 => array('name' => 'break lever bm150', 'quantity' => '13', 'buying_price' => '60', 'selling_price' => '100', 'min' => '20', 'max' => '4'),
            26 => array('name' => 'break lever cg150', 'quantity' => '14', 'buying_price' => '70', 'selling_price' => '100', 'min' => '21', 'max' => '4'),
            27 => array('name' => 'break pads bm150-yog', 'quantity' => '49', 'buying_price' => '140', 'selling_price' => '200', 'min' => '74', 'max' => '15'),
            28 => array('name' => 'break pads tvs*', 'quantity' => '7', 'buying_price' => '140', 'selling_price' => '200', 'min' => '11', 'max' => '3'),
            29 => array('name' => 'break pedal spring cg150', 'quantity' => '20', 'buying_price' => '15', 'selling_price' => '50', 'min' => '30', 'max' => '6'),
            30 => array('name' => 'break rod bm150', 'quantity' => '20', 'buying_price' => '50', 'selling_price' => '150', 'min' => '30', 'max' => '6'),
            31 => array('name' => 'break rod cg150', 'quantity' => '20', 'buying_price' => '50', 'selling_price' => '150', 'min' => '30', 'max' => '6'),
            32 => array('name' => 'break shoe cg150 t-max', 'quantity' => '20', 'buying_price' => '115', 'selling_price' => '180', 'min' => '30', 'max' => '6'),
            33 => array('name' => 'bulb holder bm150', 'quantity' => '9', 'buying_price' => '90', 'selling_price' => '150', 'min' => '14', 'max' => '3'),
            34 => array('name' => 'bulb holder cg150', 'quantity' => '31', 'buying_price' => '25', 'selling_price' => '100', 'min' => '47', 'max' => '9'),
            35 => array('name' => 'cam follower', 'quantity' => '9', 'buying_price' => '200', 'selling_price' => '400', 'min' => '14', 'max' => '3'),
            36 => array('name' => 'cam shaft', 'quantity' => '6', 'buying_price' => '400', 'selling_price' => '600', 'min' => '9', 'max' => '3'),
            37 => array('name' => 'camshaft bm150', 'quantity' => '6', 'buying_price' => '550', 'selling_price' => '800', 'min' => '9', 'max' => '3'),
            38 => array('name' => 'camshaft cg150', 'quantity' => '9', 'buying_price' => '400', 'selling_price' => '600', 'min' => '14', 'max' => '3'),
            39 => array('name' => 'carburator bm150', 'quantity' => '5', 'buying_price' => '980', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            40 => array('name' => 'carburator cg150', 'quantity' => '4', 'buying_price' => '600', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            41 => array('name' => 'carrier cg150', 'quantity' => '2', 'buying_price' => '3500', 'selling_price' => '4500', 'min' => '8', 'max' => '3'),
            42 => array('name' => 'cdi bm150', 'quantity' => '4', 'buying_price' => '450', 'selling_price' => '600', 'min' => '8', 'max' => '3'),
            43 => array('name' => 'cdi cg150', 'quantity' => '6', 'buying_price' => '200', 'selling_price' => '300', 'min' => '9', 'max' => '3'),
            44 => array('name' => 'cdi honda', 'quantity' => '1', 'buying_price' => '600', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            45 => array('name' => 'ceat 300*18', 'quantity' => '2', 'buying_price' => '2450', 'selling_price' => '2800', 'min' => '8', 'max' => '3'),
            46 => array('name' => 'ceat 300*90*100', 'quantity' => '5', 'buying_price' => '2450', 'selling_price' => '2800', 'min' => '8', 'max' => '3'),
            47 => array('name' => 'centeaxle hlx150', 'quantity' => '10', 'buying_price' => '100', 'selling_price' => '150', 'min' => '15', 'max' => '3'),
            48 => array('name' => 'centre axle bm100', 'quantity' => '5', 'buying_price' => '100', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            49 => array('name' => 'centre axle bm150', 'quantity' => '20', 'buying_price' => '110', 'selling_price' => '150', 'min' => '30', 'max' => '6'),
            50 => array('name' => 'centre axle cg150', 'quantity' => '16', 'buying_price' => '80', 'selling_price' => '150', 'min' => '24', 'max' => '5'),
            51 => array('name' => 'chain adjuster cg150', 'quantity' => '10', 'buying_price' => '100', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            52 => array('name' => 'chain box bm150', 'quantity' => '1', 'buying_price' => '700', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            53 => array('name' => 'chain drive cg150', 'quantity' => '5', 'buying_price' => '270', 'selling_price' => '400', 'min' => '8', 'max' => '3'),
            54 => array('name' => 'chain system bm150-yog', 'quantity' => '13', 'buying_price' => '580', 'selling_price' => '800', 'min' => '20', 'max' => '4'),
            55 => array('name' => 'chain system star', 'quantity' => '5', 'buying_price' => '560', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            56 => array('name' => 'chest guard', 'quantity' => '5', 'buying_price' => '450', 'selling_price' => '650', 'min' => '8', 'max' => '3'),
            57 => array('name' => 'clutch arm cg150', 'quantity' => '20', 'buying_price' => '120', 'selling_price' => '200', 'min' => '30', 'max' => '6'),
            58 => array('name' => 'clutch bearing bm150', 'quantity' => '18', 'buying_price' => '50', 'selling_price' => '200', 'min' => '27', 'max' => '5'),
            59 => array('name' => 'clutch cable bm150', 'quantity' => '24', 'buying_price' => '70', 'selling_price' => '150', 'min' => '36', 'max' => '7'),
            60 => array('name' => 'clutch cable cg150', 'quantity' => '18', 'buying_price' => '65', 'selling_price' => '150', 'min' => '27', 'max' => '5'),
            61 => array('name' => 'clutch cable wy150/125', 'quantity' => '12', 'buying_price' => '70', 'selling_price' => '150', 'min' => '18', 'max' => '4'),
            62 => array('name' => 'clutch complete cg150', 'quantity' => '4', 'buying_price' => '500', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            63 => array('name' => 'clutch cover gasket bm150', 'quantity' => '22', 'buying_price' => '30', 'selling_price' => '50', 'min' => '33', 'max' => '7'),
            64 => array('name' => 'clutch cover gasket cg150', 'quantity' => '23', 'buying_price' => '20', 'selling_price' => '50', 'min' => '35', 'max' => '7'),
            65 => array('name' => 'clutch disk bm150', 'quantity' => '4', 'buying_price' => '350', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            66 => array('name' => 'clutch housing bm150', 'quantity' => '1', 'buying_price' => '1200', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            67 => array('name' => 'clutch lever bm150', 'quantity' => '4', 'buying_price' => '70', 'selling_price' => '100', 'min' => '8', 'max' => '3'),
            68 => array('name' => 'clutch lever cg150', 'quantity' => '12', 'buying_price' => '550', 'selling_price' => '800', 'min' => '18', 'max' => '4'),
            69 => array('name' => 'clutch plate bm150', 'quantity' => '6', 'buying_price' => '150', 'selling_price' => '200', 'min' => '9', 'max' => '3'),
            70 => array('name' => 'clutch plate cb125', 'quantity' => '5', 'buying_price' => '100', 'selling_price' => '250', 'min' => '8', 'max' => '3'),
            71 => array('name' => 'clutch plate cg150', 'quantity' => '19', 'buying_price' => '140', 'selling_price' => '200', 'min' => '29', 'max' => '6'),
            72 => array('name' => 'clutch plate cg150', 'quantity' => '8', 'buying_price' => '150', 'selling_price' => '200', 'min' => '12', 'max' => '3'),
            73 => array('name' => 'cowling cover bm150', 'quantity' => '16', 'buying_price' => '250', 'selling_price' => '600', 'min' => '24', 'max' => '5'),
            74 => array('name' => 'crank shaft cg150', 'quantity' => '4', 'buying_price' => '1650', 'selling_price' => '2500', 'min' => '8', 'max' => '3'),
            75 => array('name' => 'crankshaft bm150', 'quantity' => '1', 'buying_price' => '1700', 'selling_price' => '3000', 'min' => '8', 'max' => '3'),
            76 => array('name' => 'cylinder block bm150', 'quantity' => '2', 'buying_price' => '1400', 'selling_price' => '2500', 'min' => '8', 'max' => '3'),
            77 => array('name' => 'cylinder block cg150', 'quantity' => '3', 'buying_price' => '1400', 'selling_price' => '2500', 'min' => '8', 'max' => '3'),
            78 => array('name' => 'cylinder head gasket bm150', 'quantity' => '8', 'buying_price' => '30', 'selling_price' => '50', 'min' => '12', 'max' => '3'),
            79 => array('name' => 'cylinder head gasket cg150', 'quantity' => '40', 'buying_price' => '25', 'selling_price' => '50', 'min' => '60', 'max' => '12'),
            80 => array('name' => 'dashboard bm150', 'quantity' => '4', 'buying_price' => '900', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            81 => array('name' => 'dashboard cg150', 'quantity' => '2', 'buying_price' => '900', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            82 => array('name' => 'dimmer bm150', 'quantity' => '4', 'buying_price' => '600', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            83 => array('name' => 'dimmer hlx150', 'quantity' => '2', 'buying_price' => '550', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            84 => array('name' => 'dimmer switch', 'quantity' => '9', 'buying_price' => '150', 'selling_price' => '300', 'min' => '14', 'max' => '3'),
            85 => array('name' => 'dimmer switch bm150', 'quantity' => '4', 'buying_price' => '600', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            86 => array('name' => 'dimmer switch honda', 'quantity' => '2', 'buying_price' => '600', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            87 => array('name' => 'dimmer tvs *', 'quantity' => '3', 'buying_price' => '500', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            88 => array('name' => 'double stand cg150', 'quantity' => '2', 'buying_price' => '550', 'selling_price' => '750', 'min' => '8', 'max' => '3'),
            89 => array('name' => 'drive chain yog', 'quantity' => '5', 'buying_price' => '300', 'selling_price' => '430', 'min' => '8', 'max' => '3'),
            90 => array('name' => 'drive set bm', 'quantity' => '2', 'buying_price' => '700', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            91 => array('name' => 'drive set cg 150', 'quantity' => '5', 'buying_price' => '680', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            92 => array('name' => 'drive set hlx150', 'quantity' => '7', 'buying_price' => '700', 'selling_price' => '900', 'min' => '11', 'max' => '3'),
            93 => array('name' => 'drive shaft bm150', 'quantity' => '4', 'buying_price' => '300', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            94 => array('name' => 'drive shaft cg150', 'quantity' => '3', 'buying_price' => '450', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            95 => array('name' => 'drive shaft cg150', 'quantity' => '10', 'buying_price' => '160', 'selling_price' => '400', 'min' => '15', 'max' => '3'),
            96 => array('name' => 'engine oil seals', 'quantity' => '45', 'buying_price' => '30', 'selling_price' => '50', 'min' => '68', 'max' => '14'),
            97 => array('name' => 'engine valve bm150-yog', 'quantity' => '19', 'buying_price' => '150', 'selling_price' => '200', 'min' => '29', 'max' => '6'),
            98 => array('name' => 'flahser bm150', 'quantity' => '30', 'buying_price' => '70', 'selling_price' => '150', 'min' => '45', 'max' => '9'),
            99 => array('name' => 'flahser unit cg150', 'quantity' => '5', 'buying_price' => '80', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            100 => array('name' => 'flasher bm150', 'quantity' => '2', 'buying_price' => '80', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            101 => array('name' => 'flasher unit bm150', 'quantity' => '19', 'buying_price' => '70', 'selling_price' => '150', 'min' => '29', 'max' => '6'),
            102 => array('name' => 'foot rest rubber cg150', 'quantity' => '10', 'buying_price' => '170', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            103 => array('name' => 'front mudguard bm150 red', 'quantity' => '5', 'buying_price' => '230', 'selling_price' => '400', 'min' => '8', 'max' => '3'),
            104 => array('name' => 'front muguard cg150', 'quantity' => '11', 'buying_price' => '280', 'selling_price' => '400', 'min' => '17', 'max' => '3'),
            105 => array('name' => 'front shocks bm150', 'quantity' => '1', 'buying_price' => '3200', 'selling_price' => '4500', 'min' => '8', 'max' => '3'),
            106 => array('name' => 'front shocks cg150', 'quantity' => '2', 'buying_price' => '2450', 'selling_price' => '3000', 'min' => '8', 'max' => '3'),
            107 => array('name' => 'front sprocket lock bm150', 'quantity' => '3', 'buying_price' => '30', 'selling_price' => '50', 'min' => '8', 'max' => '3'),
            108 => array('name' => 'front sprocket lock cg150', 'quantity' => '22', 'buying_price' => '30', 'selling_price' => '50', 'min' => '33', 'max' => '7'),
            109 => array('name' => 'fuel tap', 'quantity' => '4', 'buying_price' => '280', 'selling_price' => '350', 'min' => '8', 'max' => '3'),
            110 => array('name' => 'gasket honda', 'quantity' => '4', 'buying_price' => '150', 'selling_price' => '200', 'min' => '8', 'max' => '3'),
            111 => array('name' => 'gear box cg150', 'quantity' => '2', 'buying_price' => '900', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            112 => array('name' => 'gear box roller bearing bm150', 'quantity' => '9', 'buying_price' => '200', 'selling_price' => '500', 'min' => '14', 'max' => '3'),
            113 => array('name' => 'gear lever bm150', 'quantity' => '3', 'buying_price' => '150', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            114 => array('name' => 'gear lever cg150', 'quantity' => '10', 'buying_price' => '130', 'selling_price' => '250', 'min' => '15', 'max' => '3'),
            115 => array('name' => 'gear shaft boxer150', 'quantity' => '5', 'buying_price' => '280', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            116 => array('name' => 'gear shaft cg150', 'quantity' => '3', 'buying_price' => '450', 'selling_price' => '600', 'min' => '8', 'max' => '3'),
            117 => array('name' => 'half axle bm150', 'quantity' => '7', 'buying_price' => '100', 'selling_price' => '200', 'min' => '11', 'max' => '3'),
            118 => array('name' => 'half gasket bm150', 'quantity' => '37', 'buying_price' => '70', 'selling_price' => '200', 'min' => '56', 'max' => '11'),
            119 => array('name' => 'handle bar bm150', 'quantity' => '2', 'buying_price' => '300', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            120 => array('name' => 'handle bar tvs*', 'quantity' => '2', 'buying_price' => '300', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            121 => array('name' => 'handle grip bm150', 'quantity' => '10', 'buying_price' => '100', 'selling_price' => '150', 'min' => '15', 'max' => '3'),
            122 => array('name' => 'handle grips', 'quantity' => '25', 'buying_price' => '70', 'selling_price' => '200', 'min' => '38', 'max' => '8'),
            123 => array('name' => 'headlamp assy cg150', 'quantity' => '6', 'buying_price' => '450', 'selling_price' => '700', 'min' => '9', 'max' => '3'),
            124 => array('name' => 'headlight bm150', 'quantity' => '5', 'buying_price' => '400', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            125 => array('name' => 'headlight bulb bm150', 'quantity' => '15', 'buying_price' => '45', 'selling_price' => '150', 'min' => '23', 'max' => '5'),
            126 => array('name' => 'headlight bulb halogen', 'quantity' => '21', 'buying_price' => '50', 'selling_price' => '100', 'min' => '32', 'max' => '6'),
            127 => array('name' => 'helme deletion', 'quantity' => '1', 'buying_price' => '700', 'selling_price' => '1100', 'min' => '8', 'max' => '3'),
            128 => array('name' => 'helmet half', 'quantity' => '4', 'buying_price' => '650', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            129 => array('name' => 'helmet point', 'quantity' => '5', 'buying_price' => '650', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            130 => array('name' => 'helmet visor bm', 'quantity' => '8', 'buying_price' => '130', 'selling_price' => '150', 'min' => '12', 'max' => '3'),
            131 => array('name' => 'helmet visor half', 'quantity' => '22', 'buying_price' => '80', 'selling_price' => '150', 'min' => '33', 'max' => '7'),
            132 => array('name' => 'honda oil', 'quantity' => '5', 'buying_price' => '480', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            133 => array('name' => 'horn', 'quantity' => '10', 'buying_price' => '100', 'selling_price' => '200', 'min' => '15', 'max' => '3'),
            134 => array('name' => 'horn pararira', 'quantity' => '3', 'buying_price' => '400', 'selling_price' => '600', 'min' => '8', 'max' => '3'),
            135 => array('name' => 'ignition switch bm150', 'quantity' => '7', 'buying_price' => '250', 'selling_price' => '400', 'min' => '11', 'max' => '3'),
            136 => array('name' => 'ignition switch cg150', 'quantity' => '6', 'buying_price' => '190', 'selling_price' => '300', 'min' => '9', 'max' => '3'),
            137 => array('name' => 'indicator banana cg150', 'quantity' => '15', 'buying_price' => '75', 'selling_price' => '150', 'min' => '23', 'max' => '5'),
            138 => array('name' => 'indicator bm', 'quantity' => '17', 'buying_price' => '70', 'selling_price' => '150', 'min' => '26', 'max' => '5'),
            139 => array('name' => 'indicator bulb', 'quantity' => '180', 'buying_price' => '7', 'selling_price' => '10', 'min' => '270', 'max' => '54'),
            140 => array('name' => 'indicator cb125 ace rear', 'quantity' => '4', 'buying_price' => '210', 'selling_price' => '350', 'min' => '8', 'max' => '3'),
            141 => array('name' => 'indicator cg150 sqaure', 'quantity' => '5', 'buying_price' => '100', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            142 => array('name' => 'indicator switch', 'quantity' => '12', 'buying_price' => '200', 'selling_price' => '350', 'min' => '18', 'max' => '4'),
            143 => array('name' => 'inner clutch wire', 'quantity' => '55', 'buying_price' => '25', 'selling_price' => '50', 'min' => '83', 'max' => '17'),
            144 => array('name' => 'insulating tape', 'quantity' => '24', 'buying_price' => '25', 'selling_price' => '30', 'min' => '36', 'max' => '7'),
            145 => array('name' => 'insurance holder', 'quantity' => '22', 'buying_price' => '30', 'selling_price' => '50', 'min' => '33', 'max' => '7'),
            146 => array('name' => 'kick shaft cg150', 'quantity' => '5', 'buying_price' => '380', 'selling_price' => '600', 'min' => '8', 'max' => '3'),
            147 => array('name' => 'kick start s', 'quantity' => '6', 'buying_price' => '150', 'selling_price' => '300', 'min' => '9', 'max' => '3'),
            148 => array('name' => 'lead wire', 'quantity' => '13', 'buying_price' => '50', 'selling_price' => '100', 'min' => '20', 'max' => '4'),
            149 => array('name' => 'led ibdicator', 'quantity' => '10', 'buying_price' => '100', 'selling_price' => '200', 'min' => '15', 'max' => '3'),
            150 => array('name' => 'left swicth tvs*', 'quantity' => '1', 'buying_price' => '500', 'selling_price' => '900', 'min' => '8', 'max' => '3'),
            151 => array('name' => 'lines decorations', 'quantity' => '160', 'buying_price' => '6', 'selling_price' => '10', 'min' => '240', 'max' => '48'),
            152 => array('name' => 'lines lights', 'quantity' => '26', 'buying_price' => '130', 'selling_price' => '200', 'min' => '39', 'max' => '8'),
            153 => array('name' => 'magnet coil cg150', 'quantity' => '7', 'buying_price' => '480', 'selling_price' => '800', 'min' => '11', 'max' => '3'),
            154 => array('name' => 'magneto bm150', 'quantity' => '4', 'buying_price' => '800', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            155 => array('name' => 'magneto coil hlx150', 'quantity' => '1', 'buying_price' => '1000', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            156 => array('name' => 'magneto coil tvs', 'quantity' => '2', 'buying_price' => '500', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            157 => array('name' => 'magneto cover gasket cg150', 'quantity' => '33', 'buying_price' => '25', 'selling_price' => '50', 'min' => '50', 'max' => '10'),
            158 => array('name' => 'main switch bm150 yog', 'quantity' => '5', 'buying_price' => '290', 'selling_price' => '400', 'min' => '8', 'max' => '3'),
            159 => array('name' => 'mirror holder assy bm150', 'quantity' => '13', 'buying_price' => '250', 'selling_price' => '400', 'min' => '20', 'max' => '4'),
            160 => array('name' => 'mirror holder bm150', 'quantity' => '20', 'buying_price' => '80', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            161 => array('name' => 'mirror holder cg150', 'quantity' => '18', 'buying_price' => '110', 'selling_price' => '100', 'min' => '27', 'max' => '5'),
            162 => array('name' => 'monster', 'quantity' => '19', 'buying_price' => '130', 'selling_price' => '200', 'min' => '29', 'max' => '6'),
            163 => array('name' => 'motorol', 'quantity' => '2', 'buying_price' => '325', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            164 => array('name' => 'neck bearing cg150', 'quantity' => '11', 'buying_price' => '120', 'selling_price' => '300', 'min' => '17', 'max' => '3'),
            165 => array('name' => 'oil cup', 'quantity' => '5', 'buying_price' => '145', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            166 => array('name' => 'oil filter bm', 'quantity' => '40', 'buying_price' => '70', 'selling_price' => '100', 'min' => '60', 'max' => '12'),
            167 => array('name' => 'oil pump cg150', 'quantity' => '2', 'buying_price' => '250', 'selling_price' => '350', 'min' => '8', 'max' => '3'),
            168 => array('name' => 'oil seal kit bm150', 'quantity' => '40', 'buying_price' => '45', 'selling_price' => '100', 'min' => '60', 'max' => '12'),
            169 => array('name' => 'oil seal magnet cg150', 'quantity' => '20', 'buying_price' => '60', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            170 => array('name' => 'oil shock seals cg150', 'quantity' => '82', 'buying_price' => '50', 'selling_price' => '100', 'min' => '123', 'max' => '25'),
            171 => array('name' => 'oil shocks front', 'quantity' => '20', 'buying_price' => '30', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            172 => array('name' => 'ordinary tube 300*17', 'quantity' => '22', 'buying_price' => '150', 'selling_price' => '250', 'min' => '33', 'max' => '7'),
            173 => array('name' => 'piston kit bm150', 'quantity' => '8', 'buying_price' => '390', 'selling_price' => '600', 'min' => '12', 'max' => '3'),
            174 => array('name' => 'piston kit cg150 std+', 'quantity' => '20', 'buying_price' => '230', 'selling_price' => '500', 'min' => '30', 'max' => '6'),
            175 => array('name' => 'piston kit cg150 std++', 'quantity' => '15', 'buying_price' => '230', 'selling_price' => '500', 'min' => '23', 'max' => '5'),
            176 => array('name' => 'piston kit tvs*', 'quantity' => '2', 'buying_price' => '500', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            177 => array('name' => 'piston ring bm150', 'quantity' => '12', 'buying_price' => '100', 'selling_price' => '200', 'min' => '18', 'max' => '4'),
            178 => array('name' => 'piston rings cg150+', 'quantity' => '20', 'buying_price' => '140', 'selling_price' => '200', 'min' => '30', 'max' => '6'),
            179 => array('name' => 'piston rings tvs std+', 'quantity' => '9', 'buying_price' => '140', 'selling_price' => '200', 'min' => '14', 'max' => '3'),
            180 => array('name' => 'plug cap cg150', 'quantity' => '21', 'buying_price' => '70', 'selling_price' => '100', 'min' => '32', 'max' => '6'),
            181 => array('name' => 'push rod cg150', 'quantity' => '11', 'buying_price' => '100', 'selling_price' => '200', 'min' => '17', 'max' => '3'),
            182 => array('name' => 'radio', 'quantity' => '5', 'buying_price' => '1000', 'selling_price' => '1500', 'min' => '8', 'max' => '3'),
            183 => array('name' => 'radio apple', 'quantity' => '3', 'buying_price' => '1000', 'selling_price' => '1400', 'min' => '8', 'max' => '3'),
            184 => array('name' => 'radio tyre', 'quantity' => '3', 'buying_price' => '2000', 'selling_price' => '3000', 'min' => '8', 'max' => '3'),
            185 => array('name' => 'rain coat', 'quantity' => '2', 'buying_price' => '1200', 'selling_price' => '1700', 'min' => '8', 'max' => '3'),
            186 => array('name' => 'rear axle cg150', 'quantity' => '19', 'buying_price' => '90', 'selling_price' => '150', 'min' => '29', 'max' => '6'),
            187 => array('name' => 'rear break switch', 'quantity' => '28', 'buying_price' => '60', 'selling_price' => '100', 'min' => '42', 'max' => '8'),
            188 => array('name' => 'rear shocks bm150-yog', 'quantity' => '3', 'buying_price' => '970', 'selling_price' => '1400', 'min' => '8', 'max' => '3'),
            189 => array('name' => 'rear sprocket cg150', 'quantity' => '5', 'buying_price' => '270', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            190 => array('name' => 'regulator cg150', 'quantity' => '2', 'buying_price' => '200', 'selling_price' => '400', 'min' => '8', 'max' => '3'),
            191 => array('name' => 'return spring bm150', 'quantity' => '20', 'buying_price' => '70', 'selling_price' => '500', 'min' => '30', 'max' => '6'),
            192 => array('name' => 'rim cg150', 'quantity' => '1', 'buying_price' => '2700', 'selling_price' => '3200', 'min' => '8', 'max' => '3'),
            193 => array('name' => 'rings cg150 std+', 'quantity' => '20', 'buying_price' => '50', 'selling_price' => '200', 'min' => '30', 'max' => '6'),
            194 => array('name' => 'rings cg150 std++', 'quantity' => '40', 'buying_price' => '50', 'selling_price' => '200', 'min' => '60', 'max' => '12'),
            195 => array('name' => 'rings cg150 std+++', 'quantity' => '10', 'buying_price' => '80', 'selling_price' => '200', 'min' => '15', 'max' => '3'),
            196 => array('name' => 'rings honda', 'quantity' => '4', 'buying_price' => '180', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            197 => array('name' => 'rocker arm', 'quantity' => '5', 'buying_price' => '650', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            198 => array('name' => 'roller bearing cg150', 'quantity' => '10', 'buying_price' => '140', 'selling_price' => '350', 'min' => '15', 'max' => '3'),
            199 => array('name' => 'rr shocks cg150', 'quantity' => '3', 'buying_price' => '1300', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            200 => array('name' => 'seat cg150', 'quantity' => '3', 'buying_price' => '1150', 'selling_price' => '1600', 'min' => '8', 'max' => '3'),
            201 => array('name' => 'sharp light', 'quantity' => '20', 'buying_price' => '60', 'selling_price' => '100', 'min' => '30', 'max' => '6'),
            202 => array('name' => 'shell advance oil', 'quantity' => '36', 'buying_price' => '325', 'selling_price' => '350', 'min' => '54', 'max' => '11'),
            203 => array('name' => 'shock absorber oil', 'quantity' => '12', 'buying_price' => '100', 'selling_price' => '150', 'min' => '18', 'max' => '4'),
            204 => array('name' => 'shock boots rubbers', 'quantity' => '23', 'buying_price' => '100', 'selling_price' => '200', 'min' => '35', 'max' => '7'),
            205 => array('name' => 'shock lifter cg150', 'quantity' => '10', 'buying_price' => '60', 'selling_price' => '100', 'min' => '15', 'max' => '3'),
            206 => array('name' => 'shocks bm150', 'quantity' => '1', 'buying_price' => '1400', 'selling_price' => '2000', 'min' => '8', 'max' => '3'),
            207 => array('name' => 'shooting coil cg150', 'quantity' => '4', 'buying_price' => '260', 'selling_price' => '350', 'min' => '8', 'max' => '3'),
            208 => array('name' => 'side cover bm150', 'quantity' => '7', 'buying_price' => '250', 'selling_price' => '500', 'min' => '11', 'max' => '3'),
            209 => array('name' => 'side cover cg150', 'quantity' => '3', 'buying_price' => '400', 'selling_price' => '450', 'min' => '8', 'max' => '3'),
            210 => array('name' => 'side cover cg150', 'quantity' => '8', 'buying_price' => '225', 'selling_price' => '450', 'min' => '12', 'max' => '3'),
            211 => array('name' => 'side cover lock bm150', 'quantity' => '10', 'buying_price' => '90', 'selling_price' => '150', 'min' => '15', 'max' => '3'),
            212 => array('name' => 'side cover lock cg150', 'quantity' => '21', 'buying_price' => '30', 'selling_price' => '50', 'min' => '32', 'max' => '6'),
            213 => array('name' => 'side mirror bm100 round', 'quantity' => '12', 'buying_price' => '100', 'selling_price' => '150', 'min' => '18', 'max' => '4'),
            214 => array('name' => 'side mirror cg150-5 corners', 'quantity' => '25', 'buying_price' => '75', 'selling_price' => '150', 'min' => '38', 'max' => '8'),
            215 => array('name' => 'side mirror cg150-square', 'quantity' => '49', 'buying_price' => '75', 'selling_price' => '150', 'min' => '74', 'max' => '15'),
            216 => array('name' => 'side mirror chrome', 'quantity' => '20', 'buying_price' => '260', 'selling_price' => '400', 'min' => '30', 'max' => '6'),
            217 => array('name' => 'side mirror hlx150', 'quantity' => '14', 'buying_price' => '200', 'selling_price' => '400', 'min' => '21', 'max' => '4'),
            218 => array('name' => 'side mirror hlx150', 'quantity' => '10', 'buying_price' => '200', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            219 => array('name' => 'side mirror honda', 'quantity' => '4', 'buying_price' => '200', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            220 => array('name' => 'side mirrorbm 150', 'quantity' => '18', 'buying_price' => '150', 'selling_price' => '300', 'min' => '27', 'max' => '5'),
            221 => array('name' => 'silicon', 'quantity' => '28', 'buying_price' => '40', 'selling_price' => '50', 'min' => '42', 'max' => '8'),
            222 => array('name' => 'spark plug 7h', 'quantity' => '21', 'buying_price' => '50', 'selling_price' => '100', 'min' => '32', 'max' => '6'),
            223 => array('name' => 'spark plug d8ea', 'quantity' => '35', 'buying_price' => '50', 'selling_price' => '100', 'min' => '53', 'max' => '11'),
            224 => array('name' => 'spark plug long range hlx150', 'quantity' => '4', 'buying_price' => '40', 'selling_price' => '100', 'min' => '8', 'max' => '3'),
            225 => array('name' => 'speed cable cg150', 'quantity' => '4', 'buying_price' => '70', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            226 => array('name' => 'speedo cable cb125', 'quantity' => '5', 'buying_price' => '70', 'selling_price' => '150', 'min' => '8', 'max' => '3'),
            227 => array('name' => 'sport light', 'quantity' => '4', 'buying_price' => '300', 'selling_price' => '650', 'min' => '8', 'max' => '3'),
            228 => array('name' => 'sprocket holder cg150', 'quantity' => '6', 'buying_price' => '35', 'selling_price' => '50', 'min' => '9', 'max' => '3'),
            229 => array('name' => 'sprocket seeting', 'quantity' => '6', 'buying_price' => '300', 'selling_price' => '500', 'min' => '9', 'max' => '3'),
            230 => array('name' => 'sprocket sitting bm150', 'quantity' => '5', 'buying_price' => '400', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            231 => array('name' => 'sprocket studs bm150', 'quantity' => '10', 'buying_price' => '50', 'selling_price' => '200', 'min' => '15', 'max' => '3'),
            232 => array('name' => 'sprocket studs tvs', 'quantity' => '28', 'buying_price' => '30', 'selling_price' => '50', 'min' => '42', 'max' => '8'),
            233 => array('name' => 'standard bulb cg150', 'quantity' => '16', 'buying_price' => '25', 'selling_price' => '50', 'min' => '24', 'max' => '5'),
            234 => array('name' => 'stator motor', 'quantity' => '3', 'buying_price' => '900', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            235 => array('name' => 'steel mudguard', 'quantity' => '3', 'buying_price' => '450', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            236 => array('name' => 'super glue', 'quantity' => '50', 'buying_price' => '25', 'selling_price' => '30', 'min' => '75', 'max' => '15'),
            237 => array('name' => 'super run 300*18', 'quantity' => '1', 'buying_price' => '1700', 'selling_price' => '2000', 'min' => '8', 'max' => '3'),
            238 => array('name' => 'tail lamp bulb', 'quantity' => '77', 'buying_price' => '10', 'selling_price' => '30', 'min' => '116', 'max' => '23'),
            239 => array('name' => 'tail lamp com', 'quantity' => '5', 'buying_price' => '700', 'selling_price' => '100', 'min' => '8', 'max' => '3'),
            240 => array('name' => 'tail lamp tvs', 'quantity' => '3', 'buying_price' => '280', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            241 => array('name' => 'tail light bm150', 'quantity' => '2', 'buying_price' => '150', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            242 => array('name' => 'tail mudguard', 'quantity' => '10', 'buying_price' => '160', 'selling_price' => '400', 'min' => '15', 'max' => '3'),
            243 => array('name' => 'tank covers bm150', 'quantity' => '4', 'buying_price' => '250', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            244 => array('name' => 'tank covers cg150', 'quantity' => '4', 'buying_price' => '350', 'selling_price' => '500', 'min' => '8', 'max' => '3'),
            245 => array('name' => 'tensioner guide bm150', 'quantity' => '9', 'buying_price' => '150', 'selling_price' => '500', 'min' => '14', 'max' => '3'),
            246 => array('name' => 'tensioner stick bm150', 'quantity' => '20', 'buying_price' => '90', 'selling_price' => '300', 'min' => '30', 'max' => '6'),
            247 => array('name' => 'throttle cable bm150', 'quantity' => '20', 'buying_price' => '65', 'selling_price' => '150', 'min' => '30', 'max' => '6'),
            248 => array('name' => 'timing chain bm150', 'quantity' => '6', 'buying_price' => '150', 'selling_price' => '200', 'min' => '9', 'max' => '3'),
            249 => array('name' => 'timing chain bm150', 'quantity' => '20', 'buying_price' => '80', 'selling_price' => '200', 'min' => '30', 'max' => '6'),
            250 => array('name' => 'timing sprocket bm150', 'quantity' => '5', 'buying_price' => '150', 'selling_price' => '200', 'min' => '8', 'max' => '3'),
            251 => array('name' => 'total classic', 'quantity' => '7', 'buying_price' => '272.22', 'selling_price' => '300', 'min' => '11', 'max' => '3'),
            252 => array('name' => 'tube 2.75*17 yog', 'quantity' => '10', 'buying_price' => '120', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            253 => array('name' => 'tube 3.00*18 yog', 'quantity' => '20', 'buying_price' => '160', 'selling_price' => '300', 'min' => '30', 'max' => '6'),
            254 => array('name' => 'tube 300*17-yog', 'quantity' => '18', 'buying_price' => '200', 'selling_price' => '300', 'min' => '27', 'max' => '5'),
            255 => array('name' => 'tube 300*18-yog', 'quantity' => '13', 'buying_price' => '200', 'selling_price' => '300', 'min' => '20', 'max' => '4'),
            256 => array('name' => 'tube ordinary 300*18-cc', 'quantity' => '16', 'buying_price' => '150', 'selling_price' => '250', 'min' => '24', 'max' => '5'),
            257 => array('name' => 'tutor', 'quantity' => '10', 'buying_price' => '230', 'selling_price' => '300', 'min' => '15', 'max' => '3'),
            258 => array('name' => 'tyre 250*17-prodrive', 'quantity' => '1', 'buying_price' => '980', 'selling_price' => '1200', 'min' => '8', 'max' => '3'),
            259 => array('name' => 'tyre 275*18 cc', 'quantity' => '4', 'buying_price' => '1200', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            260 => array('name' => 'tyre 275*18-prodrive', 'quantity' => '1', 'buying_price' => '850', 'selling_price' => '1200', 'min' => '8', 'max' => '3'),
            261 => array('name' => 'tyre 300* 17-cc', 'quantity' => '2', 'buying_price' => '1350', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            262 => array('name' => 'tyre cc 300*18', 'quantity' => '1', 'buying_price' => '1350', 'selling_price' => '1800', 'min' => '8', 'max' => '3'),
            263 => array('name' => 'u bolt', 'quantity' => '40', 'buying_price' => '30', 'selling_price' => '100', 'min' => '60', 'max' => '12'),
            264 => array('name' => 'valve cg150-yog', 'quantity' => '30', 'buying_price' => '150', 'selling_price' => '200', 'min' => '45', 'max' => '9'),
            265 => array('name' => 'valve honda', 'quantity' => '4', 'buying_price' => '180', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            266 => array('name' => 'valve tvs*', 'quantity' => '19', 'buying_price' => '150', 'selling_price' => '200', 'min' => '29', 'max' => '6'),
            267 => array('name' => 'valve tvs*', 'quantity' => '2', 'buying_price' => '150', 'selling_price' => '200', 'min' => '8', 'max' => '3'),
            268 => array('name' => 'visor', 'quantity' => '10', 'buying_price' => '250', 'selling_price' => '400', 'min' => '15', 'max' => '3'),
            269 => array('name' => 'visor hlx150', 'quantity' => '1', 'buying_price' => '1550', 'selling_price' => '2500', 'min' => '8', 'max' => '3'),
            270 => array('name' => 'washer no 10', 'quantity' => '50', 'buying_price' => '3', 'selling_price' => '5', 'min' => '75', 'max' => '15'),
            271 => array('name' => 'washer no 13', 'quantity' => '0', 'buying_price' => '10', 'selling_price' => '20', 'min' => '8', 'max' => '3'),
            272 => array('name' => 'washer no 17', 'quantity' => '2', 'buying_price' => '10', 'selling_price' => '20', 'min' => '8', 'max' => '3'),
            273 => array('name' => 'washer no 19', 'quantity' => '17', 'buying_price' => '10', 'selling_price' => '20', 'min' => '26', 'max' => '5'),
            274 => array('name' => 'washer no 20', 'quantity' => '0', 'buying_price' => '10', 'selling_price' => '10', 'min' => '8', 'max' => '3'),
            275 => array('name' => 'washer no 8', 'quantity' => '50', 'buying_price' => '2', 'selling_price' => '5', 'min' => '75', 'max' => '15'),
            276 => array('name' => 'wheel bushes', 'quantity' => '4', 'buying_price' => '100', 'selling_price' => '300', 'min' => '8', 'max' => '3'),
            277 => array('name' => 'wind screen', 'quantity' => '3', 'buying_price' => '650', 'selling_price' => '800', 'min' => '8', 'max' => '3'),
            278 => array('name' => 'wire hireness cg150', 'quantity' => '4', 'buying_price' => '400', 'selling_price' => '700', 'min' => '8', 'max' => '3'),
            279 => array('name' => 'wirehireness tvs*', 'quantity' => '2', 'buying_price' => '450', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
            280 => array('name' => 'wiring system bm150', 'quantity' => '5', 'buying_price' => '450', 'selling_price' => '1000', 'min' => '8', 'max' => '3'),
        );;;

        if (Product::count() === 0) {
            foreach ($products as $product) {
                $created_product = Product::create([
                    'name' => $product['name'],
                    'buying_price' => $product['buying_price'],
                    'buying_price_currency' => 'KES',
                    'selling_price_currency' => 'KES',
                    'selling_price' => $product['selling_price'],
                    'min' => $product['max'],
                    'max' => $product['min']
                ]);
                $created_product->purchases()->create([
                    'quantity' => $product['quantity'],
                    'unit_price' => $product['buying_price'],
                    'currency' => 'KES',
                    'purchase_date' => '2020-05-14'
                ]);
            }
        }
    }
}
